export const SCHEMA_STATEMENTS: string[] = [
  `PRAGMA journal_mode = WAL;`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    email TEXT,
    avatar_uri TEXT,
    weight_kg REAL,
    height_cm REAL,
    age INTEGER,
    gender TEXT,
    activity_level TEXT,
    health_goals TEXT NOT NULL DEFAULT '[]',
    dietary_restrictions TEXT NOT NULL DEFAULT '[]',
    preferred_language TEXT NOT NULL DEFAULT 'en',
    onboarding_completed INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS receipts (
    id TEXT PRIMARY KEY NOT NULL,
    image_uri TEXT NOT NULL,
    raw_ocr_text TEXT NOT NULL,
    store_name TEXT,
    store_address TEXT,
    currency TEXT NOT NULL DEFAULT 'USD',
    total_amount REAL,
    detected_language TEXT,
    scan_date INTEGER NOT NULL,
    created_at INTEGER NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS expense_items (
    id TEXT PRIMARY KEY NOT NULL,
    receipt_id TEXT NOT NULL,
    catalog_id TEXT,
    name TEXT NOT NULL,
    name_translated TEXT,
    category TEXT NOT NULL DEFAULT 'other',
    subcategory TEXT,
    quantity REAL NOT NULL DEFAULT 1,
    unit TEXT NOT NULL DEFAULT 'pcs',
    unit_price REAL,
    total_price REAL NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    purchase_date INTEGER NOT NULL,
    expiry_date INTEGER,
    brand TEXT,
    barcode TEXT,
    tags TEXT NOT NULL DEFAULT '[]',
    notes TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (receipt_id) REFERENCES receipts(id)
  );`,
  `CREATE TABLE IF NOT EXISTS nutrition_profiles (
    id TEXT PRIMARY KEY NOT NULL,
    expense_item_id TEXT NOT NULL,
    source TEXT NOT NULL,
    serving_size_g REAL,
    servings_per_container REAL,
    calories REAL,
    protein_g REAL,
    carbs_g REAL,
    fat_g REAL,
    fiber_g REAL,
    sugar_g REAL,
    saturated_fat_g REAL,
    trans_fat_g REAL,
    unsaturated_fat_g REAL,
    sodium_mg REAL,
    potassium_mg REAL,
    calcium_mg REAL,
    iron_mg REAL,
    magnesium_mg REAL,
    vitamin_a_mcg REAL,
    vitamin_c_mg REAL,
    vitamin_d_mcg REAL,
    vitamin_e_mg REAL,
    vitamin_k_mcg REAL,
    vitamin_b1_mg REAL,
    vitamin_b2_mg REAL,
    vitamin_b3_mg REAL,
    vitamin_b6_mg REAL,
    vitamin_b12_mcg REAL,
    folate_mcg REAL,
    zinc_mg REAL,
    selenium_mcg REAL,
    cholesterol_mg REAL,
    ai_confidence_score REAL,
    raw_label_text TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (expense_item_id) REFERENCES expense_items(id)
  );`,
  `CREATE TABLE IF NOT EXISTS daily_nutrition_logs (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    log_date INTEGER NOT NULL,
    expense_item_id TEXT NOT NULL,
    consumed_servings REAL NOT NULL DEFAULT 1,
    calories REAL,
    protein_g REAL,
    carbs_g REAL,
    fat_g REAL,
    fiber_g REAL,
    sugar_g REAL,
    sodium_mg REAL,
    confidence_score REAL,
    source TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (expense_item_id) REFERENCES expense_items(id)
  );`,
  `CREATE TABLE IF NOT EXISTS health_alerts (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    alert_type TEXT NOT NULL,
    nutrient_key TEXT,
    current_value REAL,
    target_value REAL,
    severity TEXT NOT NULL,
    message TEXT NOT NULL,
    message_translated TEXT,
    is_read INTEGER NOT NULL DEFAULT 0,
    triggered_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    icon TEXT,
    color TEXT,
    parent_id TEXT,
    user_id TEXT
  );`,
  `CREATE TABLE IF NOT EXISTS household_profiles (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL DEFAULT 'My Household',
    meals_per_day INTEGER NOT NULL DEFAULT 3,
    grocery_frequency TEXT NOT NULL DEFAULT 'weekly',
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS family_members (
    id TEXT PRIMARY KEY NOT NULL,
    household_id TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT,
    age INTEGER,
    gender TEXT,
    weight_kg REAL,
    height_cm REAL,
    is_school_age INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    rda_profile_key TEXT,
    rda_targets TEXT NOT NULL DEFAULT '{}',
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (household_id) REFERENCES household_profiles(id)
  );`,
  `CREATE TABLE IF NOT EXISTS item_category_memory (
    normalized_name TEXT PRIMARY KEY NOT NULL,
    category TEXT NOT NULL,
    subcategory TEXT,
    confidence REAL NOT NULL DEFAULT 1,
    use_count INTEGER NOT NULL DEFAULT 1,
    last_seen_at INTEGER NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS receipt_corrections (
    id TEXT PRIMARY KEY NOT NULL,
    item_name_original TEXT NOT NULL,
    item_name_corrected TEXT NOT NULL,
    confidence_before REAL,
    created_at INTEGER NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS barcode_nutrition_cache (
    barcode TEXT PRIMARY KEY NOT NULL,
    payload_json TEXT NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS nutrition_analytics_snapshots (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    from_ts INTEGER NOT NULL,
    to_ts INTEGER NOT NULL,
    reliability_score REAL NOT NULL,
    coverage_score REAL NOT NULL,
    anomaly_count INTEGER NOT NULL DEFAULT 0,
    metrics_json TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
  );`,
  `CREATE TABLE IF NOT EXISTS consumption_models (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    expense_item_id TEXT NOT NULL,
    avg_daily_servings REAL NOT NULL DEFAULT 0,
    trend_slope REAL NOT NULL DEFAULT 0,
    variability REAL NOT NULL DEFAULT 0,
    confidence REAL NOT NULL DEFAULT 0,
    last_predicted_depletion INTEGER,
    updated_at INTEGER NOT NULL,
    UNIQUE(user_id, expense_item_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (expense_item_id) REFERENCES expense_items(id)
  );`,
  `CREATE INDEX IF NOT EXISTS idx_expense_items_purchase_category ON expense_items (purchase_date, category);`,
  `CREATE INDEX IF NOT EXISTS idx_daily_logs_date_user ON daily_nutrition_logs (log_date, user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_alerts_user_read ON health_alerts (user_id, is_read);`,
  `CREATE INDEX IF NOT EXISTS idx_family_members_household ON family_members (household_id);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_user_to ON nutrition_analytics_snapshots (user_id, to_ts DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_consumption_models_user ON consumption_models (user_id, confidence DESC);`,
  `CREATE TABLE IF NOT EXISTS product_catalog (
    id TEXT PRIMARY KEY NOT NULL,
    normalized_name TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    display_name_translated TEXT,
    category TEXT NOT NULL DEFAULT 'grocery',
    subcategory TEXT,
    brand TEXT,
    barcode TEXT,
    is_food INTEGER NOT NULL DEFAULT 1,
    nutrition_json TEXT,
    nutrition_source TEXT,
    nutrition_confidence REAL,
    nutrition_updated_at INTEGER,
    tags TEXT NOT NULL DEFAULT '[]',
    first_seen_at INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    purchase_count INTEGER NOT NULL DEFAULT 1,
    avg_price REAL,
    min_price REAL,
    max_price REAL,
    last_price REAL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_product_catalog_normalized ON product_catalog (normalized_name);`,
  `CREATE INDEX IF NOT EXISTS idx_product_catalog_category ON product_catalog (category);`,
  `CREATE INDEX IF NOT EXISTS idx_product_catalog_barcode ON product_catalog (barcode) WHERE barcode IS NOT NULL;`,
  `CREATE INDEX IF NOT EXISTS idx_expense_items_catalog ON expense_items (catalog_id) WHERE catalog_id IS NOT NULL;`,
  `CREATE TABLE IF NOT EXISTS nutrition_name_cache (
    normalized_name TEXT PRIMARY KEY NOT NULL,
    payload_json TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'ai_inferred',
    confidence REAL NOT NULL DEFAULT 0.7,
    hit_count INTEGER NOT NULL DEFAULT 1,
    updated_at INTEGER NOT NULL
  );`,
  `CREATE VIRTUAL TABLE IF NOT EXISTS expense_items_fts USING fts5(id, name, content='expense_items', content_rowid='rowid');`,
  `CREATE TRIGGER IF NOT EXISTS expense_items_ai AFTER INSERT ON expense_items BEGIN
      INSERT INTO expense_items_fts(rowid, id, name) VALUES (new.rowid, new.id, new.name);
    END;`,
  `CREATE TRIGGER IF NOT EXISTS expense_items_ad AFTER DELETE ON expense_items BEGIN
      INSERT INTO expense_items_fts(expense_items_fts, rowid, id, name) VALUES('delete', old.rowid, old.id, old.name);
    END;`,
  `CREATE TRIGGER IF NOT EXISTS expense_items_au AFTER UPDATE ON expense_items BEGIN
      INSERT INTO expense_items_fts(expense_items_fts, rowid, id, name) VALUES('delete', old.rowid, old.id, old.name);
      INSERT INTO expense_items_fts(rowid, id, name) VALUES (new.rowid, new.id, new.name);
    END;`,
];
